name: 问题与 BUG 反馈
description: 问题反馈应当使用此模板进行提交
labels: [ bug ]
body:
  - type: markdown
    attributes:
      value: |        
        ### 请在下方填写问题发生的具体原因和复现步骤。
        
        发生异常、崩溃、闪退或功能性问题，必须提交问题 Log (日志)，没有 Log 的 issues 将直接被关闭。
  - type: input
    attributes:
      label: 模块版本
      description: 请填写当前使用的模块完整版本号，例如：**1.0**
    validations:
      required: true
  - type: input
    attributes:
      label: 正在使用的设备型号以及使用的系统
      description: 这里填写当前使用的设备型号以及使用的系统，系统例如 (MIUI、ColorOS、OxygenOS、PE/原生)
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Android 版本
      options:
        - 14
        - 13
        - 12L/12.1
        - 12
        - 11
        - 10
        - 9
        - 8.1
        - 8.0.0
        - 7.1.2
        - 7.1.1
        - 7.0
    validations:
      required: true
  - type: input
    attributes:
      label: Xposed 框架名称与版本号
      description: 请填写当前使用的 Xposed 框架，例如：**LSPosed 1.8.4 (次版本号)**
    validations:
      required: true
  - type: textarea
    attributes:
      label: 详细描述问题发生的具体原因
      description: 请在下方详细描述问题发生的具体场景、复现步骤和经过，以便我们能够按照你所描述的步骤复现这个问题。
    validations:
      required: true
  - type: textarea
    attributes:
      label: 提供模块问题 Log 或必要 Log
      description: 需要提交在runtime.log文件中与问题相关部分的日志。
      value: |
        <details><summary>展开查看</summary><pre><code>

        (此处粘贴问题 Log)

        </code></pre></details>
        <!-- 提交时可以将个人信息脱敏，粘贴你复制的日志，不要破坏代码格式 -->
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: 确认一下你提交的信息
      description: 为了确保 issues 的质量和避免浪费不必要的时间，未勾选下方选项的 issues 将直接被关闭。
      options:
        - label: 我确保上述信息准确无误
          required: true
